<a href="https://colab.research.google.com/github/Chandu106/Data_Science_Fundamentals/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **DataTypes and Attributes**

In [2]:
#1-D array
a1 = np.array([1, 2, 3])

#2-D array
a2 = np.array([[1, 2.5, 3.3],
               [4, 5, 6.5]])

#3-D array
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [6]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [7]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [8]:
a1

array([1, 2, 3])

In [9]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# **Anatomy of an array**

In [11]:
#pandas dataframe out of numpy arrays

import pandas as pd
df = pd.DataFrame(np.random.randint(10, size = (5,3)),
                  columns = ['a', 'b', 'c'])
df

a  b  c
0  6  1  4
1  7  0  4
2  6  8  1
3  0  0  7
4  7  1  2

In [12]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [13]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.5  3.3
1  4.0  5.0  6.5

In [15]:
simple_array = np.array([1,2,3])
simple_array, simple_array.dtype, type(simple_array)

(array([1, 2, 3]), dtype('int64'), numpy.ndarray)

In [16]:
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [19]:
zeros = np.zeros(shape=(5,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
zeros.dtype

dtype('float64')

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array1 = np.random.randint(10, size=(5, 3))
random_array1

array([[6, 0, 5],
       [6, 2, 4],
       [1, 8, 0],
       [2, 6, 9],
       [5, 6, 7]])

In [24]:
random_array2 = np.random.random(size = (5,3))
random_array2

array([[0.8297718 , 0.19774615, 0.13211542],
       [0.19796055, 0.20702291, 0.15647322],
       [0.75790058, 0.06525392, 0.20861242],
       [0.84820454, 0.80458045, 0.31381835],
       [0.1320869 , 0.94598098, 0.68130356]])

In [27]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.15873528, 0.92260027, 0.83729449],
       [0.49761586, 0.10748258, 0.75754121],
       [0.2010736 , 0.48748463, 0.62197987],
       [0.76612929, 0.91921238, 0.55740919],
       [0.98829386, 0.91654019, 0.44242017]])

In [30]:
#random seed repeats the random values without any change, if in doubt run the code
np.random.seed(0)
np.random.randint(10, size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [36]:
np.random.seed(0)
random_array4 = np.random.randint(10, size=(5,3))
df2 = pd.DataFrame(random_array4,
                   columns=['a', 'b', 'c'])
df2

a  b  c
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [37]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [39]:
a1

array([1, 2, 3])

In [40]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [42]:
a1[0]

1

In [43]:
a2[0]

array([1. , 2.5, 3.3])

In [44]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a2[1]

array([4. , 5. , 6.5])

In [46]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [47]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
a3.shape

(2, 3, 3)

In [50]:
a3[:, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [52]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]])

In [53]:
a4.shape

(2, 3, 4, 5)

In [54]:
a4.ndim

4

In [55]:
a4[:,:,:,:4]

array([[[[8, 8, 2, 3],
         [0, 8, 8, 3],
         [2, 8, 4, 3],
         [4, 3, 6, 9]],

        [[0, 8, 5, 9],
         [9, 6, 5, 3],
         [8, 0, 4, 9],
         [5, 7, 8, 8]],

        [[2, 8, 6, 6],
         [1, 6, 8, 8],
         [2, 3, 6, 3],
         [5, 7, 0, 8]]],


       [[[6, 5, 8, 2],
         [9, 7, 5, 3],
         [5, 3, 3, 7],
         [9, 9, 7, 3]],

        [[3, 9, 7, 7],
         [1, 2, 2, 8],
         [5, 8, 4, 0],
         [5, 5, 0, 8]],

        [[1, 0, 3, 8],
         [4, 4, 0, 9],
         [7, 3, 2, 1],
         [2, 1, 4, 2]]]])

In [56]:
a1

array([1, 2, 3])

In [57]:
ones = np.ones(shape=(3))
ones

array([1., 1., 1.])

In [58]:
a1 + ones

array([2., 3., 4.])

In [59]:
a1 - ones

array([0., 1., 2.])

In [60]:
a1 * ones

array([1., 2., 3.])

In [61]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [62]:
a1 * a2

array([[ 1. ,  5. ,  9.9],
       [ 4. , 10. , 19.5]])

In [63]:
a1.shape, a2.shape

((3,), (2, 3))

In [64]:
a2.shape

(2, 3)

In [65]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [66]:
a2 * a3

ValueError: ignored

In [67]:
a1 / ones


array([1., 2., 3.])

In [68]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [69]:
a1 ** 2

array([1, 4, 9])

In [70]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [71]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [72]:
sum(a1)

6

In [73]:
np.sum(a1)

6

In [78]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [79]:
%timeit sum(massive_array)  #python sum()
%timeit np.sum(massive_array) #NumPy np.sum()

10.7 ms ± 3.19 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
39.7 µs ± 195 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [80]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [81]:
np.mean(a2)

3.716666666666667

In [82]:
np.max(a2)

6.5

In [83]:
np.min(a2)

1.0

In [84]:
np.std(a2)

1.756337730114064

In [85]:
np.var(a2)

3.084722222222222

In [86]:
np.sqrt(np.var(a2))

1.756337730114064

# **Reshaping**

In [87]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [88]:
a2.shape

(2, 3)

In [89]:
a2 + a3

ValueError: ignored

In [90]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2.5],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [92]:
a2.reshape(2, 3, 1) + a3

array([[[ 2. ,  3. ,  4. ],
        [ 6.5,  7.5,  8.5],
        [10.3, 11.3, 12.3]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22.5, 23.5, 24.5]]])

# **Transpose**

In [93]:
a2.shape

(2, 3)

In [94]:
a2.T

array([[1. , 4. ],
       [2.5, 5. ],
       [3.3, 6.5]])

In [95]:
a2.T.shape

(3, 2)

In [100]:
matrix = np.random.random(size=(5,3,4))
matrix

array([[[0.19921624, 0.16466691, 0.16130836, 0.0039912 ],
        [0.89840508, 0.34486382, 0.74635132, 0.44772775],
        [0.89349213, 0.65112679, 0.12954539, 0.96642218]],

       [[0.31838338, 0.67196883, 0.31724311, 0.98328964],
        [0.82931282, 0.98022729, 0.20208123, 0.02280128],
        [0.0540468 , 0.28335266, 0.6742351 , 0.63960552]],

       [[0.32378148, 0.64389754, 0.18334675, 0.18894126],
        [0.1859126 , 0.65671056, 0.04619239, 0.87818728],
        [0.373481  , 0.30350368, 0.03611455, 0.02423069]],

       [[0.09122017, 0.08091936, 0.66249122, 0.08001905],
        [0.34557956, 0.06358647, 0.23513018, 0.83936412],
        [0.11803496, 0.34342701, 0.58912512, 0.56331109]],

       [[0.44705182, 0.65720129, 0.42287264, 0.28922578],
        [0.2213997 , 0.46189199, 0.0546558 , 0.91246367],
        [0.61790558, 0.29124117, 0.65501202, 0.5891504 ]]])

In [101]:
matrix.shape

(5, 3, 4)

In [102]:
matrix.T

array([[[0.19921624, 0.31838338, 0.32378148, 0.09122017, 0.44705182],
        [0.89840508, 0.82931282, 0.1859126 , 0.34557956, 0.2213997 ],
        [0.89349213, 0.0540468 , 0.373481  , 0.11803496, 0.61790558]],

       [[0.16466691, 0.67196883, 0.64389754, 0.08091936, 0.65720129],
        [0.34486382, 0.98022729, 0.65671056, 0.06358647, 0.46189199],
        [0.65112679, 0.28335266, 0.30350368, 0.34342701, 0.29124117]],

       [[0.16130836, 0.31724311, 0.18334675, 0.66249122, 0.42287264],
        [0.74635132, 0.20208123, 0.04619239, 0.23513018, 0.0546558 ],
        [0.12954539, 0.6742351 , 0.03611455, 0.58912512, 0.65501202]],

       [[0.0039912 , 0.98328964, 0.18894126, 0.08001905, 0.28922578],
        [0.44772775, 0.02280128, 0.87818728, 0.83936412, 0.91246367],
        [0.96642218, 0.63960552, 0.02423069, 0.56331109, 0.5891504 ]]])

In [103]:
matrix.T.shape

(4, 3, 5)