<a href="https://colab.research.google.com/github/Chandu106/Data_Science_Fundamentals/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **DataTypes and Attributes**

In [2]:
#1-D array
a1 = np.array([1, 2, 3])

#2-D array
a2 = np.array([[1, 2.5, 3.3],
               [4, 5, 6.5]])

#3-D array
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [3]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [5]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [6]:
a1

array([1, 2, 3])

In [7]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# **Anatomy of an array**

In [9]:
#pandas dataframe out of numpy arrays

import pandas as pd
df = pd.DataFrame(np.random.randint(10, size = (5,3)),
                  columns = ['a', 'b', 'c'])
df

a  b  c
0  5  0  3
1  1  3  8
2  7  9  7
3  1  8  2
4  4  4  5

In [10]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [11]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.5  3.3
1  4.0  5.0  6.5

In [12]:
simple_array = np.array([1,2,3])
simple_array, simple_array.dtype, type(simple_array)

(array([1, 2, 3]), dtype('int64'), numpy.ndarray)

In [13]:
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
ones.dtype

dtype('float64')

In [15]:
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [16]:
zeros = np.zeros(shape=(5,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array1 = np.random.randint(10, size=(5, 3))
random_array1

array([[2, 1, 2],
       [1, 8, 9],
       [6, 0, 8],
       [6, 6, 6],
       [6, 9, 7]])

In [20]:
random_array2 = np.random.random(size = (5,3))
random_array2

array([[0.42629609, 0.87085549, 0.61423574],
       [0.7314529 , 0.71796072, 0.54147347],
       [0.3642021 , 0.59999356, 0.70502692],
       [0.79974069, 0.75748297, 0.46159469],
       [0.73815127, 0.30079812, 0.09220144]])

In [21]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.40938484, 0.61001551, 0.3821103 ],
       [0.81919021, 0.56902278, 0.754445  ],
       [0.30509813, 0.41382445, 0.34115765],
       [0.10053676, 0.04322525, 0.89758534],
       [0.3020516 , 0.25317115, 0.11404476]])

In [22]:
#random seed repeats the random values without any change, if in doubt run the code
np.random.seed(0)
np.random.randint(10, size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [23]:
np.random.seed(0)
random_array4 = np.random.randint(10, size=(5,3))
df2 = pd.DataFrame(random_array4,
                   columns=['a', 'b', 'c'])
df2

a  b  c
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [24]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [26]:
a1

array([1, 2, 3])

In [27]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
a1[0]

1

In [30]:
a2[0]

array([1. , 2.5, 3.3])

In [31]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a2[1]

array([4. , 5. , 6.5])

In [33]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a3.shape

(2, 3, 3)

In [36]:
a3[:, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [38]:
a4.shape

(2, 3, 4, 5)

In [39]:
a4.ndim

4

In [40]:
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

In [41]:
a1

array([1, 2, 3])

In [42]:
ones = np.ones(shape=(3))
ones

array([1., 1., 1.])

In [43]:
a1 + ones

array([2., 3., 4.])

In [44]:
a1 - ones

array([0., 1., 2.])

In [45]:
a1 * ones

array([1., 2., 3.])

In [46]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [47]:
a1 * a2

array([[ 1. ,  5. ,  9.9],
       [ 4. , 10. , 19.5]])

In [48]:
a1.shape, a2.shape

((3,), (2, 3))

In [49]:
a2.shape

(2, 3)

In [50]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [51]:
a2 * a3

ValueError: ignored

In [52]:
a1 / ones


array([1., 2., 3.])

In [53]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [54]:
a1 ** 2

array([1, 4, 9])

In [55]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [56]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [57]:
sum(a1)

6

In [58]:
np.sum(a1)

6

In [59]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [60]:
%timeit sum(massive_array)  #python sum()
%timeit np.sum(massive_array) #NumPy np.sum()

8.07 ms ± 1.62 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
26.5 µs ± 565 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [61]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [62]:
np.mean(a2)

3.716666666666667

In [63]:
np.max(a2)

6.5

In [64]:
np.min(a2)

1.0

In [65]:
np.std(a2)

1.756337730114064

In [66]:
np.var(a2)

3.084722222222222

In [67]:
np.sqrt(np.var(a2))

1.756337730114064

# **Reshaping**

In [68]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [69]:
a2.shape

(2, 3)

In [70]:
a2 + a3

ValueError: ignored

In [71]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2.5],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [72]:
a2.reshape(2, 3, 1) + a3

array([[[ 2. ,  3. ,  4. ],
        [ 6.5,  7.5,  8.5],
        [10.3, 11.3, 12.3]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22.5, 23.5, 24.5]]])

# **Transpose**

In [73]:
a2.shape

(2, 3)

In [74]:
a2.T

array([[1. , 4. ],
       [2.5, 5. ],
       [3.3, 6.5]])

In [75]:
a2.T.shape

(3, 2)

In [76]:
matrix = np.random.random(size=(5,3,4))
matrix

array([[[0.59816399, 0.17370251, 0.49752936, 0.51231935],
        [0.41529741, 0.44150892, 0.96844105, 0.23242417],
        [0.90336451, 0.35172075, 0.56481088, 0.57771134]],

       [[0.73115238, 0.88762934, 0.37368847, 0.35104994],
        [0.11873224, 0.72324236, 0.93202688, 0.09600718],
        [0.4330638 , 0.71979707, 0.06689016, 0.20815443]],

       [[0.55415679, 0.08416165, 0.88953996, 0.00301345],
        [0.30163886, 0.12337636, 0.13435611, 0.51987339],
        [0.05418991, 0.11426417, 0.19005404, 0.61364183]],

       [[0.23385887, 0.13555752, 0.32546415, 0.81922614],
        [0.94551446, 0.12975713, 0.35431267, 0.37758386],
        [0.07987885, 0.5011568 , 0.02229736, 0.13672066]],

       [[0.54215489, 0.32970332, 0.79006968, 0.03848783],
        [0.31634927, 0.12626378, 0.0490067 , 0.55428092],
        [0.30483769, 0.61825824, 0.97796585, 0.43375406]]])

In [77]:
matrix.shape

(5, 3, 4)

In [78]:
matrix.T

array([[[0.59816399, 0.73115238, 0.55415679, 0.23385887, 0.54215489],
        [0.41529741, 0.11873224, 0.30163886, 0.94551446, 0.31634927],
        [0.90336451, 0.4330638 , 0.05418991, 0.07987885, 0.30483769]],

       [[0.17370251, 0.88762934, 0.08416165, 0.13555752, 0.32970332],
        [0.44150892, 0.72324236, 0.12337636, 0.12975713, 0.12626378],
        [0.35172075, 0.71979707, 0.11426417, 0.5011568 , 0.61825824]],

       [[0.49752936, 0.37368847, 0.88953996, 0.32546415, 0.79006968],
        [0.96844105, 0.93202688, 0.13435611, 0.35431267, 0.0490067 ],
        [0.56481088, 0.06689016, 0.19005404, 0.02229736, 0.97796585]],

       [[0.51231935, 0.35104994, 0.00301345, 0.81922614, 0.03848783],
        [0.23242417, 0.09600718, 0.51987339, 0.37758386, 0.55428092],
        [0.57771134, 0.20815443, 0.61364183, 0.13672066, 0.43375406]]])

In [79]:
matrix.T.shape

(4, 3, 5)

In [80]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(3,3))
mat2 = np.random.randint(10, size=(3,3))
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]]),
 array([[4, 7, 6],
        [8, 8, 1],
        [6, 7, 7]]))

In [81]:
np.dot(mat1, mat2)

array([[ 38,  56,  51],
       [122, 140,  88],
       [ 64,  75,  37]])

In [82]:
np.random.seed(0)
mat3 = np.random.randint(10, size=(4,3))
mat4 = np.random.randint(10, size=(4,3))
mat3, mat4

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]]),
 array([[8, 8, 1],
        [6, 7, 7],
        [8, 1, 5],
        [9, 8, 9]]))

In [83]:
np.dot(mat3, mat4)

ValueError: ignored

In [84]:
mat3.T.shape

(3, 4)

In [86]:
np.dot(mat3.T, mat4)

array([[118,  96,  77],
       [145, 110, 137],
       [148, 137, 130]])

In [87]:
mat3 * mat4

array([[40,  0,  3],
       [18, 49, 63],
       [24,  5, 10],
       [36, 56, 54]])

# **Comparison Operators**

In [88]:
a1

array([1, 2, 3])

In [89]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5. , 6.5]])

In [90]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [91]:
a1 >= a2

array([[ True, False, False],
       [False, False, False]])

In [92]:
a1 == a2

array([[ True, False, False],
       [False, False, False]])

# **Sortiing Arrays**

In [94]:
random_array1

array([[2, 1, 2],
       [1, 8, 9],
       [6, 0, 8],
       [6, 6, 6],
       [6, 9, 7]])

In [96]:
np.sort(random_array1)

array([[1, 2, 2],
       [1, 8, 9],
       [0, 6, 8],
       [6, 6, 6],
       [6, 7, 9]])

In [97]:
np.argsort(random_array1)

array([[1, 0, 2],
       [0, 1, 2],
       [1, 0, 2],
       [0, 1, 2],
       [0, 2, 1]])

In [98]:
a1

array([1, 2, 3])

In [99]:
np.argsort(a1)

array([0, 1, 2])

In [100]:
np.argmin(a1)

0

In [101]:
np.argmax(a1)

2

# **Weekly sales report**

In [102]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [103]:
weekly_sales = pd.DataFrame(sales_amount,
                            index=["Mon", "Tue", "Wed", "Thu", "Fri"],
                            columns=["Chicken", "Paneer", "Mushroom"])
weekly_sales

Chicken  Paneer  Mushroom
Mon       12      15         0
Tue        3       3         7
Wed        9      19        18
Thu        4       6        12
Fri        1       6         7

In [104]:
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [107]:
items_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                            columns=["Chicken", "Paneer", "Mushroom"])
items_prices

Chicken  Paneer  Mushroom
Price       10       8        12

In [108]:
total_sales = prices.dot(sales_amount)
total_sales

ValueError: ignored

In [109]:
sales_amount.shape

(5, 3)

In [110]:
prices.shape

(3,)

In [112]:
sales_amount.T.shape

(3, 5)

In [114]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [115]:
prices.shape, weekly_sales.shape

((3,), (5, 3))

In [116]:
dialy_sales = prices.dot(weekly_sales.T)
dialy_sales

array([240, 138, 458, 232, 142])

In [117]:
weekly_sales["Total"] = dialy_sales.T
weekly_sales

Chicken  Paneer  Mushroom  Total
Mon       12      15         0    240
Tue        3       3         7    138
Wed        9      19        18    458
Thu        4       6        12    232
Fri        1       6         7    142